// Generated by CoffeeScript 1.3.3

$('#getSuggestions').live('pagebeforecreate', function() {
  return $('.collapser').live('click', function(e) {
    if ($(this).hasClass('open')) {
      console.log('close please');
      $(this).parent().next().removeClass('open').addClass('closed');
      return $(this).removeClass('open').addClass('closed');
    } else {
      $(this).parent().next().removeClass('closed').addClass('open');
      return $(this).removeClass('closed').addClass('open');
    }
  });
});
